group "org.polypheny"


dependencies {
    compileOnly project(":core")
    compileOnly project(":dbms")
    compileOnly project(":webui")
    compileOnly project(":plugins:sql-language")
    compileOnly project(":plugins:postgres-adapter")

    compileOnly project(":plugins:mql-language")
    compileOnly project(":plugins:mongodb-adapter")

    compileOnly project(":plugins:cypher-language")
    compileOnly project(":plugins:neo4j-adapter")
    compileOnly project(":plugins:notebooks")

    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: jackson_core_version

    // --- Test Compile ---
    testImplementation project(path: ":dbms", configuration: "test")
    testImplementation project(path: ":core", configuration: "tests")
    testImplementation project(path: ":core")
    testImplementation project(path: ":webui")
    testImplementation project(path: ":plugins:sql-language")
}

delombok {
    dependsOn(":config:processResources")
    dependsOn(":core:processResources")
    dependsOn(":information:processResources")
    dependsOn(":webui:processResources")

    dependsOn(":plugins:sql-language:processResources")
    dependsOn(":plugins:postgres-adapter:processResources")

    dependsOn(":plugins:mql-language:processResources")
    dependsOn(":plugins:mongodb-adapter:processResources")

    dependsOn(":plugins:cypher-language:processResources")
    dependsOn(":plugins:neo4j-adapter:processResources")

    dependsOn(":plugins:notebooks:processResources")
}


sourceSets {
    main {
        java {
            srcDirs = ["src/main/java"]
        }
        resources {
            srcDirs = ["src/main/resources"]
        }
        output.resourcesDir = file(project.buildDir.absolutePath + "/classes")
    }
    test {
        java {
            srcDirs = ["src/test/java"]
            destinationDirectory.set(file(project.buildDir.absolutePath + "/test-classes"))
        }
        resources {
            srcDirs = ["src/test/resources"]
        }
        output.resourcesDir = file(project.buildDir.absolutePath + "/test-classes")
    }
}

compileJava {
    dependsOn(":config:processResources")
    dependsOn(":core:processResources")
    dependsOn(":information:processResources")
    dependsOn(":webui:processResources")

    dependsOn(":plugins:sql-language:processResources")
    dependsOn(":plugins:postgres-adapter:processResources")

    dependsOn(":plugins:mql-language:processResources")
    dependsOn(":plugins:mongodb-adapter:processResources")

    dependsOn(":plugins:cypher-language:processResources")
    dependsOn(":plugins:neo4j-adapter:processResources")

    dependsOn(":plugins:notebooks:processResources")
}

test.dependsOn(":dbms:shadowJar")


/**
 * JARs
 */
jar {
    manifest {
        attributes "Manifest-Version": "1.0"
        attributes "Copyright": "The Polypheny Project (polypheny.org)"
        attributes "Version": "$project.version"
    }
}
java {
    withJavadocJar()
    withSourcesJar()
}

licensee {
    allow('MIT')
    allow('Apache-2.0')
}
