/* Generated By:JavaCC: Do not edit this line. SqlParserImplConstants.java */
package org.polypheny.db.sql.parser.impl;

public interface SqlParserImplConstants {

  int EOF = 0;
  int A = 1;
  int ABS = 2;
  int ABSENT = 3;
  int ABSOLUTE = 4;
  int ACTION = 5;
  int ADA = 6;
  int ADAPTERS = 7;
  int ADD = 8;
  int ADMIN = 9;
  int AFTER = 10;
  int ALL = 11;
  int ALLOCATE = 12;
  int ALLOW = 13;
  int ALTER = 14;
  int ALWAYS = 15;
  int AND = 16;
  int ANY = 17;
  int APPLY = 18;
  int ARE = 19;
  int ARRAY = 20;
  int ARRAY_MAX_CARDINALITY = 21;
  int AS = 22;
  int ASC = 23;
  int ASENSITIVE = 24;
  int ASSERTION = 25;
  int ASSIGNMENT = 26;
  int ASYMMETRIC = 27;
  int AT = 28;
  int ATOMIC = 29;
  int ATTRIBUTE = 30;
  int ATTRIBUTES = 31;
  int AUTHORIZATION = 32;
  int AVG = 33;
  int BEFORE = 34;
  int BEGIN = 35;
  int BEGIN_FRAME = 36;
  int BEGIN_PARTITION = 37;
  int BERNOULLI = 38;
  int BETWEEN = 39;
  int BIGINT = 40;
  int BINARY = 41;
  int BIT = 42;
  int BLOB = 43;
  int BOOLEAN = 44;
  int BOTH = 45;
  int BREADTH = 46;
  int BY = 47;
  int C = 48;
  int CALL = 49;
  int CALLED = 50;
  int CARDINALITY = 51;
  int CASCADE = 52;
  int CASCADED = 53;
  int CASE = 54;
  int CAST = 55;
  int CATALOG = 56;
  int CATALOG_NAME = 57;
  int CEIL = 58;
  int CEILING = 59;
  int CENTURY = 60;
  int CHAIN = 61;
  int CHAR = 62;
  int CHAR_LENGTH = 63;
  int CHARACTER = 64;
  int CHARACTER_LENGTH = 65;
  int CHARACTER_SET_CATALOG = 66;
  int CHARACTER_SET_NAME = 67;
  int CHARACTER_SET_SCHEMA = 68;
  int CHARACTERISTICS = 69;
  int CHARACTERS = 70;
  int CHECK = 71;
  int CLASSIFIER = 72;
  int CLASS_ORIGIN = 73;
  int CLOB = 74;
  int CLOSE = 75;
  int COALESCE = 76;
  int COBOL = 77;
  int COLLATE = 78;
  int COLLATION = 79;
  int COLLATION_CATALOG = 80;
  int COLLATION_NAME = 81;
  int COLLATION_SCHEMA = 82;
  int COLLECT = 83;
  int COLUMN = 84;
  int COLUMN_NAME = 85;
  int COMMAND_FUNCTION = 86;
  int COMMAND_FUNCTION_CODE = 87;
  int COMMIT = 88;
  int COMMITTED = 89;
  int CONDITION = 90;
  int CONDITIONAL = 91;
  int CONDITION_NUMBER = 92;
  int CONFIG = 93;
  int CONNECT = 94;
  int CONNECTION = 95;
  int CONNECTION_NAME = 96;
  int CONSTRAINT = 97;
  int CONSTRAINT_CATALOG = 98;
  int CONSTRAINT_NAME = 99;
  int CONSTRAINT_SCHEMA = 100;
  int CONSTRAINTS = 101;
  int CONSTRUCTOR = 102;
  int CONTAINS = 103;
  int CONTINUE = 104;
  int CONVERT = 105;
  int CORR = 106;
  int CORRESPONDING = 107;
  int COUNT = 108;
  int COVAR_POP = 109;
  int COVAR_SAMP = 110;
  int CREATE = 111;
  int CROSS = 112;
  int CUBE = 113;
  int CUME_DIST = 114;
  int CURRENT = 115;
  int CURRENT_CATALOG = 116;
  int CURRENT_DATE = 117;
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 118;
  int CURRENT_PATH = 119;
  int CURRENT_ROLE = 120;
  int CURRENT_ROW = 121;
  int CURRENT_SCHEMA = 122;
  int CURRENT_TIME = 123;
  int CURRENT_TIMESTAMP = 124;
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 125;
  int CURRENT_USER = 126;
  int CURSOR = 127;
  int CURSOR_NAME = 128;
  int CYCLE = 129;
  int DATA = 130;
  int DATABASE = 131;
  int DATE = 132;
  int DATETIME_INTERVAL_CODE = 133;
  int DATETIME_INTERVAL_PRECISION = 134;
  int DAY = 135;
  int DEALLOCATE = 136;
  int DEC = 137;
  int DECADE = 138;
  int DECIMAL = 139;
  int DECLARE = 140;
  int DEFAULT_ = 141;
  int DEFAULTS = 142;
  int DEFERRABLE = 143;
  int DEFERRED = 144;
  int DEFINE = 145;
  int DEFINED = 146;
  int DEFINER = 147;
  int DEGREE = 148;
  int DELETE = 149;
  int DENSE_RANK = 150;
  int DEPTH = 151;
  int DEREF = 152;
  int DERIVED = 153;
  int DESC = 154;
  int DESCRIBE = 155;
  int DESCRIPTION = 156;
  int DESCRIPTOR = 157;
  int DETERMINISTIC = 158;
  int DIAGNOSTICS = 159;
  int DISALLOW = 160;
  int DISCONNECT = 161;
  int DISPATCH = 162;
  int DISTINCT = 163;
  int DOCUMENT = 164;
  int DOMAIN = 165;
  int DOUBLE = 166;
  int DOW = 167;
  int DOY = 168;
  int DROP = 169;
  int DYNAMIC = 170;
  int DYNAMIC_FUNCTION = 171;
  int DYNAMIC_FUNCTION_CODE = 172;
  int EACH = 173;
  int ELEMENT = 174;
  int ELSE = 175;
  int EMPTY = 176;
  int ENCODING = 177;
  int END = 178;
  int END_EXEC = 179;
  int END_FRAME = 180;
  int END_PARTITION = 181;
  int EPOCH = 182;
  int EQUALS = 183;
  int ERROR = 184;
  int ESCAPE = 185;
  int EVERY = 186;
  int EXCEPT = 187;
  int EXCEPTION = 188;
  int EXCLUDE = 189;
  int EXCLUDING = 190;
  int EXEC = 191;
  int EXECUTE = 192;
  int EXISTS = 193;
  int EXP = 194;
  int EXPLAIN = 195;
  int EXTEND = 196;
  int EXTERNAL = 197;
  int EXTRACT = 198;
  int FALSE = 199;
  int FETCH = 200;
  int FILTER = 201;
  int FINAL = 202;
  int FIRST = 203;
  int FIRST_VALUE = 204;
  int FLOAT = 205;
  int FLOOR = 206;
  int FOLLOWING = 207;
  int FOR = 208;
  int FORMAT = 209;
  int FOREIGN = 210;
  int FORTRAN = 211;
  int FOUND = 212;
  int FRAC_SECOND = 213;
  int FRAME_ROW = 214;
  int FREE = 215;
  int FREQUENCY = 216;
  int FRESHNESS = 217;
  int FROM = 218;
  int FULL = 219;
  int FUNCTION = 220;
  int FUSION = 221;
  int G = 222;
  int GENERAL = 223;
  int GENERATED = 224;
  int GEOMETRY = 225;
  int GET = 226;
  int GLOBAL = 227;
  int GO = 228;
  int GOTO = 229;
  int GRANT = 230;
  int GRANTED = 231;
  int GROUP = 232;
  int GROUPING = 233;
  int GROUPS = 234;
  int HAVING = 235;
  int HIERARCHY = 236;
  int HOLD = 237;
  int HOUR = 238;
  int IDENTITY = 239;
  int IMAGE = 240;
  int IMMEDIATE = 241;
  int IMMEDIATELY = 242;
  int IMPLEMENTATION = 243;
  int IMPORT = 244;
  int IN = 245;
  int INCLUDING = 246;
  int INCREMENT = 247;
  int INDEX = 248;
  int INDICATOR = 249;
  int INITIAL = 250;
  int INITIALLY = 251;
  int INNER = 252;
  int INOUT = 253;
  int INPUT = 254;
  int INSENSITIVE = 255;
  int INSERT = 256;
  int INSTANCE = 257;
  int INSTANTIABLE = 258;
  int INT = 259;
  int INTEGER = 260;
  int INTERFACES = 261;
  int INTERSECT = 262;
  int INTERSECTION = 263;
  int INTERVAL = 264;
  int INTO = 265;
  int INVOKER = 266;
  int IS = 267;
  int ISODOW = 268;
  int ISOYEAR = 269;
  int ISOLATION = 270;
  int JAVA = 271;
  int JOIN = 272;
  int JSON = 273;
  int JSON_ARRAY = 274;
  int JSON_ARRAYAGG = 275;
  int JSON_EXISTS = 276;
  int JSON_VALUE = 277;
  int JSON_OBJECT = 278;
  int JSON_OBJECTAGG = 279;
  int JSON_QUERY = 280;
  int K = 281;
  int KEY = 282;
  int KEY_MEMBER = 283;
  int KEY_TYPE = 284;
  int DISTANCE = 285;
  int LABEL = 286;
  int LAG = 287;
  int LANGUAGE = 288;
  int LARGE = 289;
  int LAST = 290;
  int LAST_VALUE = 291;
  int LATERAL = 292;
  int LEAD = 293;
  int LEADING = 294;
  int LEFT = 295;
  int LENGTH = 296;
  int LEVEL = 297;
  int LIBRARY = 298;
  int LIKE = 299;
  int LIKE_REGEX = 300;
  int LIMIT = 301;
  int LN = 302;
  int LOCAL = 303;
  int LOCALTIME = 304;
  int LOCALTIMESTAMP = 305;
  int LOCATOR = 306;
  int LOWER = 307;
  int M = 308;
  int MANUAL = 309;
  int MAP = 310;
  int MATCH = 311;
  int MATCHED = 312;
  int MATCHES = 313;
  int MATCH_NUMBER = 314;
  int MATCH_RECOGNIZE = 315;
  int MATERIALIZED = 316;
  int MAX = 317;
  int MAXVALUE = 318;
  int MEASURES = 319;
  int MEMBER = 320;
  int MERGE = 321;
  int MESSAGE_LENGTH = 322;
  int MESSAGE_OCTET_LENGTH = 323;
  int MESSAGE_TEXT = 324;
  int META = 325;
  int METHOD = 326;
  int MICROSECOND = 327;
  int MILLISECOND = 328;
  int MILLENNIUM = 329;
  int MIN = 330;
  int MINUTE = 331;
  int MINVALUE = 332;
  int MOD = 333;
  int MODIFY = 334;
  int MODIFIES = 335;
  int MODULE = 336;
  int MONTH = 337;
  int MORE_ = 338;
  int MULTISET = 339;
  int MUMPS = 340;
  int NAME = 341;
  int NAMES = 342;
  int NANOSECOND = 343;
  int NATIONAL = 344;
  int NATURAL = 345;
  int NCHAR = 346;
  int NCLOB = 347;
  int NESTING = 348;
  int NEW = 349;
  int NEXT = 350;
  int NO = 351;
  int NONE = 352;
  int NORMALIZE = 353;
  int NORMALIZED = 354;
  int NOT = 355;
  int NTH_VALUE = 356;
  int NTILE = 357;
  int NULL = 358;
  int NULLABLE = 359;
  int NULLIF = 360;
  int NULLS = 361;
  int NUMBER = 362;
  int NUMERIC = 363;
  int OBJECT = 364;
  int OCCURRENCES_REGEX = 365;
  int OCTET_LENGTH = 366;
  int OCTETS = 367;
  int OF = 368;
  int OFFSET = 369;
  int OLD = 370;
  int OMIT = 371;
  int ON = 372;
  int ONE = 373;
  int ONLY = 374;
  int OPEN = 375;
  int OPTION = 376;
  int OPTIONS = 377;
  int OR = 378;
  int ORDER = 379;
  int ORDERING = 380;
  int ORDINALITY = 381;
  int OTHERS = 382;
  int OUT = 383;
  int OUTER = 384;
  int OUTPUT = 385;
  int OVER = 386;
  int OVERLAPS = 387;
  int OVERLAY = 388;
  int OVERRIDING = 389;
  int OWNER = 390;
  int PAD = 391;
  int PARAMETER = 392;
  int PARAMETER_MODE = 393;
  int PARAMETER_NAME = 394;
  int PARAMETER_ORDINAL_POSITION = 395;
  int PARAMETER_SPECIFIC_CATALOG = 396;
  int PARAMETER_SPECIFIC_NAME = 397;
  int PARAMETER_SPECIFIC_SCHEMA = 398;
  int PARTIAL = 399;
  int PARTITION = 400;
  int PARTITIONS = 401;
  int PASCAL = 402;
  int PASSING = 403;
  int PASSTHROUGH = 404;
  int PAST = 405;
  int PATH = 406;
  int PATTERN = 407;
  int PER = 408;
  int PERCENT = 409;
  int PERCENTILE_CONT = 410;
  int PERCENTILE_DISC = 411;
  int PERCENT_RANK = 412;
  int PERIOD = 413;
  int PERMUTE = 414;
  int PLACEMENT = 415;
  int PLACING = 416;
  int PLAN = 417;
  int PLI = 418;
  int PORTION = 419;
  int POSITION = 420;
  int POSITION_REGEX = 421;
  int POWER = 422;
  int PRECEDES = 423;
  int PRECEDING = 424;
  int PRECISION = 425;
  int PREPARE = 426;
  int PRESERVE = 427;
  int PREV = 428;
  int PRIMARY = 429;
  int PRIOR = 430;
  int PRIVILEGES = 431;
  int PROCEDURE = 432;
  int PUBLIC = 433;
  int QUARTER = 434;
  int RANGE = 435;
  int RANK = 436;
  int READ = 437;
  int READS = 438;
  int REAL = 439;
  int RECURSIVE = 440;
  int REF = 441;
  int REFERENCES = 442;
  int REFERENCING = 443;
  int REGR_AVGX = 444;
  int REGR_AVGY = 445;
  int REGR_COUNT = 446;
  int REGR_INTERCEPT = 447;
  int REGR_R2 = 448;
  int REGR_SLOPE = 449;
  int REGR_SXX = 450;
  int REGR_SXY = 451;
  int REGR_SYY = 452;
  int RELATIVE = 453;
  int RELEASE = 454;
  int RENAME = 455;
  int REPEATABLE = 456;
  int REPLACE = 457;
  int RESET = 458;
  int RESTART = 459;
  int RESTRICT = 460;
  int RESULT = 461;
  int RETURN = 462;
  int RETURNED_CARDINALITY = 463;
  int RETURNED_LENGTH = 464;
  int RETURNED_OCTET_LENGTH = 465;
  int RETURNED_SQLSTATE = 466;
  int RETURNING = 467;
  int RETURNS = 468;
  int REVOKE = 469;
  int RIGHT = 470;
  int ROLE = 471;
  int ROLLBACK = 472;
  int ROLLUP = 473;
  int ROUTINE = 474;
  int ROUTINE_CATALOG = 475;
  int ROUTINE_NAME = 476;
  int ROUTINE_SCHEMA = 477;
  int ROW = 478;
  int ROW_COUNT = 479;
  int ROW_NUMBER = 480;
  int ROWS = 481;
  int RUNNING = 482;
  int SAVEPOINT = 483;
  int SCALAR = 484;
  int SCALE = 485;
  int SCHEMA = 486;
  int SCHEMA_NAME = 487;
  int SCOPE = 488;
  int SCOPE_CATALOGS = 489;
  int SCOPE_NAME = 490;
  int SCOPE_SCHEMA = 491;
  int SCROLL = 492;
  int SEARCH = 493;
  int SECOND = 494;
  int SECTION = 495;
  int SECURITY = 496;
  int SEEK = 497;
  int SELECT = 498;
  int SELF = 499;
  int SENSITIVE = 500;
  int SEQUENCE = 501;
  int SERIALIZABLE = 502;
  int SERVER = 503;
  int SERVER_NAME = 504;
  int SESSION = 505;
  int SESSION_USER = 506;
  int SET = 507;
  int SETS = 508;
  int SET_MINUS = 509;
  int SHOW = 510;
  int SIMILAR = 511;
  int SIMPLE = 512;
  int SIZE = 513;
  int SKIP_ = 514;
  int SMALLINT = 515;
  int SOME = 516;
  int SOUND = 517;
  int SOURCE = 518;
  int SPACE = 519;
  int SPECIFIC = 520;
  int SPECIFIC_NAME = 521;
  int SPECIFICTYPE = 522;
  int SQL = 523;
  int SQLEXCEPTION = 524;
  int SQLSTATE = 525;
  int SQLWARNING = 526;
  int SQL_BIGINT = 527;
  int SQL_BINARY = 528;
  int SQL_BIT = 529;
  int SQL_BLOB = 530;
  int SQL_BOOLEAN = 531;
  int SQL_CHAR = 532;
  int SQL_CLOB = 533;
  int SQL_DATE = 534;
  int SQL_DECIMAL = 535;
  int SQL_DOUBLE = 536;
  int SQL_FLOAT = 537;
  int SQL_JSON = 538;
  int SQL_INTEGER = 539;
  int SQL_INTERVAL_DAY = 540;
  int SQL_INTERVAL_DAY_TO_HOUR = 541;
  int SQL_INTERVAL_DAY_TO_MINUTE = 542;
  int SQL_INTERVAL_DAY_TO_SECOND = 543;
  int SQL_INTERVAL_HOUR = 544;
  int SQL_INTERVAL_HOUR_TO_MINUTE = 545;
  int SQL_INTERVAL_HOUR_TO_SECOND = 546;
  int SQL_INTERVAL_MINUTE = 547;
  int SQL_INTERVAL_MINUTE_TO_SECOND = 548;
  int SQL_INTERVAL_MONTH = 549;
  int SQL_INTERVAL_SECOND = 550;
  int SQL_INTERVAL_YEAR = 551;
  int SQL_INTERVAL_YEAR_TO_MONTH = 552;
  int SQL_LONGVARBINARY = 553;
  int SQL_LONGVARCHAR = 554;
  int SQL_LONGVARNCHAR = 555;
  int SQL_NCHAR = 556;
  int SQL_NCLOB = 557;
  int SQL_NUMERIC = 558;
  int SQL_NVARCHAR = 559;
  int SQL_REAL = 560;
  int SQL_SMALLINT = 561;
  int SQL_TIME = 562;
  int SQL_TIMESTAMP = 563;
  int SQL_TINYINT = 564;
  int SQL_TSI_DAY = 565;
  int SQL_TSI_FRAC_SECOND = 566;
  int SQL_TSI_HOUR = 567;
  int SQL_TSI_MICROSECOND = 568;
  int SQL_TSI_MINUTE = 569;
  int SQL_TSI_MONTH = 570;
  int SQL_TSI_QUARTER = 571;
  int SQL_TSI_SECOND = 572;
  int SQL_TSI_WEEK = 573;
  int SQL_TSI_YEAR = 574;
  int SQL_VARBINARY = 575;
  int SQL_VARCHAR = 576;
  int SQRT = 577;
  int START = 578;
  int STATE = 579;
  int STATEMENT = 580;
  int STATIC = 581;
  int STDDEV_POP = 582;
  int STDDEV_SAMP = 583;
  int STORE = 584;
  int STREAM = 585;
  int STRUCTURE = 586;
  int STYLE = 587;
  int SUBCLASS_ORIGIN = 588;
  int SUBMULTISET = 589;
  int SUBSET = 590;
  int SUBSTITUTE = 591;
  int SUBSTRING = 592;
  int SUBSTRING_REGEX = 593;
  int SUCCEEDS = 594;
  int SUM = 595;
  int SYMMETRIC = 596;
  int SYSTEM = 597;
  int SYSTEM_TIME = 598;
  int SYSTEM_USER = 599;
  int TABLE = 600;
  int TABLE_NAME = 601;
  int TABLESAMPLE = 602;
  int TEMPERATURE = 603;
  int TEMPORARY = 604;
  int THEN = 605;
  int TIES = 606;
  int TIME = 607;
  int TIMESTAMP = 608;
  int TIMESTAMPADD = 609;
  int TIMESTAMPDIFF = 610;
  int TIMEZONE_HOUR = 611;
  int TIMEZONE_MINUTE = 612;
  int TINYINT = 613;
  int TO = 614;
  int TOP_LEVEL_COUNT = 615;
  int TRAILING = 616;
  int TRANSACTION = 617;
  int TRANSACTIONS_ACTIVE = 618;
  int TRANSACTIONS_COMMITTED = 619;
  int TRANSACTIONS_ROLLED_BACK = 620;
  int TRANSFORM = 621;
  int TRANSFORMS = 622;
  int TRANSLATE = 623;
  int TRANSLATE_REGEX = 624;
  int TRANSLATION = 625;
  int TREAT = 626;
  int TRIGGER = 627;
  int TRIGGER_CATALOG = 628;
  int TRIGGER_NAME = 629;
  int TRIGGER_SCHEMA = 630;
  int TRIM = 631;
  int TRIM_ARRAY = 632;
  int TRUE = 633;
  int TRUNCATE = 634;
  int TYPE = 635;
  int UESCAPE = 636;
  int UNBOUNDED = 637;
  int UNCOMMITTED = 638;
  int UNCONDITIONAL = 639;
  int UNDER = 640;
  int UNION = 641;
  int UNIQUE = 642;
  int UNKNOWN = 643;
  int UNNAMED = 644;
  int UNNEST = 645;
  int UPDATE = 646;
  int UPPER = 647;
  int UPSERT = 648;
  int USAGE = 649;
  int USER = 650;
  int USER_DEFINED_TYPE_CATALOG = 651;
  int USER_DEFINED_TYPE_CODE = 652;
  int USER_DEFINED_TYPE_NAME = 653;
  int USER_DEFINED_TYPE_SCHEMA = 654;
  int USING = 655;
  int UTF8 = 656;
  int UTF16 = 657;
  int UTF32 = 658;
  int VALUE = 659;
  int VALUES = 660;
  int VALUE_OF = 661;
  int VAR_POP = 662;
  int VAR_SAMP = 663;
  int VARBINARY = 664;
  int VARCHAR = 665;
  int VARYING = 666;
  int VERSION = 667;
  int VERSIONING = 668;
  int VIDEO = 669;
  int VIEW = 670;
  int WEEK = 671;
  int WHEN = 672;
  int WHENEVER = 673;
  int WHERE = 674;
  int WIDTH_BUCKET = 675;
  int WINDOW = 676;
  int WITH = 677;
  int WITHIN = 678;
  int WITHOUT = 679;
  int WORK = 680;
  int WRAPPER = 681;
  int WRITE = 682;
  int XML = 683;
  int YEAR = 684;
  int ZONE = 685;
  int IF = 686;
  int STORED = 687;
  int VIRTUAL = 688;
  int JAR = 689;
  int FILE = 690;
  int ARCHIVE = 691;
  int UNSIGNED_INTEGER_LITERAL = 692;
  int APPROX_NUMERIC_LITERAL = 693;
  int DECIMAL_NUMERIC_LITERAL = 694;
  int EXPONENT = 695;
  int HEXDIGIT = 696;
  int WHITESPACE = 697;
  int BINARY_STRING_LITERAL = 698;
  int QUOTED_STRING = 699;
  int PREFIXED_STRING_LITERAL = 700;
  int UNICODE_STRING_LITERAL = 701;
  int CHARSETNAME = 702;
  int UNICODE_QUOTED_ESCAPE_CHAR = 703;
  int LPAREN = 704;
  int RPAREN = 705;
  int LBRACE_D = 706;
  int LBRACE_T = 707;
  int LBRACE_TS = 708;
  int LBRACE_FN = 709;
  int LBRACE = 710;
  int RBRACE = 711;
  int LBRACKET = 712;
  int RBRACKET = 713;
  int SEMICOLON = 714;
  int DOT = 715;
  int COMMA = 716;
  int EQ = 717;
  int GT = 718;
  int LT = 719;
  int HOOK = 720;
  int COLON = 721;
  int LE = 722;
  int GE = 723;
  int NE = 724;
  int NE2 = 725;
  int PLUS = 726;
  int MINUS = 727;
  int STAR = 728;
  int SLASH = 729;
  int PERCENT_REMAINDER = 730;
  int CONCAT = 731;
  int NAMED_ARGUMENT_ASSIGNMENT = 732;
  int DOUBLE_PERIOD = 733;
  int QUOTE = 734;
  int DOUBLE_QUOTE = 735;
  int VERTICAL_BAR = 736;
  int CARET = 737;
  int DOLLAR = 738;
  int SINGLE_LINE_COMMENT = 746;
  int FORMAL_COMMENT = 747;
  int MULTI_LINE_COMMENT = 748;
  int BRACKET_QUOTED_IDENTIFIER = 750;
  int QUOTED_IDENTIFIER = 751;
  int BACK_QUOTED_IDENTIFIER = 752;
  int COLLATION_ID = 753;
  int IDENTIFIER = 754;
  int UNICODE_QUOTED_IDENTIFIER = 755;
  int LETTER = 756;
  int DIGIT = 757;
  int BEL = 758;

  int DEFAULT = 0;
  int DQID = 1;
  int BTID = 2;
  int IN_FORMAL_COMMENT = 3;
  int IN_MULTI_LINE_COMMENT = 4;

  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSENT\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADAPTERS\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"ARRAY_MAX_CARDINALITY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BEGIN_FRAME\"",
    "\"BEGIN_PARTITION\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CENTURY\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASSIFIER\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITIONAL\"",
    "\"CONDITION_NUMBER\"",
    "\"CONFIG\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONTINUE\"",
    "\"CONVERT\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_ROW\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATE\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DAY\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECADE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINE\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOCUMENT\"",
    "\"DOMAIN\"",
    "\"DOUBLE\"",
    "\"DOW\"",
    "\"DOY\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"EMPTY\"",
    "\"ENCODING\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"END_FRAME\"",
    "\"END_PARTITION\"",
    "\"EPOCH\"",
    "\"EQUALS\"",
    "\"ERROR\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTEND\"",
    "\"EXTERNAL\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORMAT\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FRAC_SECOND\"",
    "\"FRAME_ROW\"",
    "\"FREE\"",
    "\"FREQUENCY\"",
    "\"FRESHNESS\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GEOMETRY\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUPING\"",
    "\"GROUPS\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOUR\"",
    "\"IDENTITY\"",
    "\"IMAGE\"",
    "\"IMMEDIATE\"",
    "\"IMMEDIATELY\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INDEX\"",
    "\"INDICATOR\"",
    "\"INITIAL\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERFACES\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISODOW\"",
    "\"ISOYEAR\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"JSON_ARRAY\"",
    "\"JSON_ARRAYAGG\"",
    "\"JSON_EXISTS\"",
    "\"JSON_VALUE\"",
    "\"JSON_OBJECT\"",
    "\"JSON_OBJECTAGG\"",
    "\"JSON_QUERY\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"DISTANCE\"",
    "\"LABEL\"",
    "\"LAG\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEAD\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIKE_REGEX\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MANUAL\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATCHES\"",
    "\"MATCH_NUMBER\"",
    "\"MATCH_RECOGNIZE\"",
    "\"MATERIALIZED\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEASURES\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"META\"",
    "\"METHOD\"",
    "\"MICROSECOND\"",
    "\"MILLISECOND\"",
    "\"MILLENNIUM\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFY\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONTH\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NANOSECOND\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NTH_VALUE\"",
    "\"NTILE\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCCURRENCES_REGEX\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"OLD\"",
    "\"OMIT\"",
    "\"ON\"",
    "\"ONE\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"OWNER\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PARTITIONS\"",
    "\"PASCAL\"",
    "\"PASSING\"",
    "\"PASSTHROUGH\"",
    "\"PAST\"",
    "\"PATH\"",
    "\"PATTERN\"",
    "\"PER\"",
    "\"PERCENT\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PERCENT_RANK\"",
    "\"PERIOD\"",
    "\"PERMUTE\"",
    "\"PLACEMENT\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"PORTION\"",
    "\"POSITION\"",
    "\"POSITION_REGEX\"",
    "\"POWER\"",
    "\"PRECEDES\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PREV\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"QUARTER\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"RENAME\"",
    "\"REPEATABLE\"",
    "\"REPLACE\"",
    "\"RESET\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNING\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"RUNNING\"",
    "\"SAVEPOINT\"",
    "\"SCALAR\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SEEK\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"MINUS\"",
    "\"SHOW\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOUND\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQL_BIGINT\"",
    "\"SQL_BINARY\"",
    "\"SQL_BIT\"",
    "\"SQL_BLOB\"",
    "\"SQL_BOOLEAN\"",
    "\"SQL_CHAR\"",
    "\"SQL_CLOB\"",
    "\"SQL_DATE\"",
    "\"SQL_DECIMAL\"",
    "\"SQL_DOUBLE\"",
    "\"SQL_FLOAT\"",
    "\"SQL_JSON\"",
    "\"SQL_INTEGER\"",
    "\"SQL_INTERVAL_DAY\"",
    "\"SQL_INTERVAL_DAY_TO_HOUR\"",
    "\"SQL_INTERVAL_DAY_TO_MINUTE\"",
    "\"SQL_INTERVAL_DAY_TO_SECOND\"",
    "\"SQL_INTERVAL_HOUR\"",
    "\"SQL_INTERVAL_HOUR_TO_MINUTE\"",
    "\"SQL_INTERVAL_HOUR_TO_SECOND\"",
    "\"SQL_INTERVAL_MINUTE\"",
    "\"SQL_INTERVAL_MINUTE_TO_SECOND\"",
    "\"SQL_INTERVAL_MONTH\"",
    "\"SQL_INTERVAL_SECOND\"",
    "\"SQL_INTERVAL_YEAR\"",
    "\"SQL_INTERVAL_YEAR_TO_MONTH\"",
    "\"SQL_LONGVARBINARY\"",
    "\"SQL_LONGVARCHAR\"",
    "\"SQL_LONGVARNCHAR\"",
    "\"SQL_NCHAR\"",
    "\"SQL_NCLOB\"",
    "\"SQL_NUMERIC\"",
    "\"SQL_NVARCHAR\"",
    "\"SQL_REAL\"",
    "\"SQL_SMALLINT\"",
    "\"SQL_TIME\"",
    "\"SQL_TIMESTAMP\"",
    "\"SQL_TINYINT\"",
    "\"SQL_TSI_DAY\"",
    "\"SQL_TSI_FRAC_SECOND\"",
    "\"SQL_TSI_HOUR\"",
    "\"SQL_TSI_MICROSECOND\"",
    "\"SQL_TSI_MINUTE\"",
    "\"SQL_TSI_MONTH\"",
    "\"SQL_TSI_QUARTER\"",
    "\"SQL_TSI_SECOND\"",
    "\"SQL_TSI_WEEK\"",
    "\"SQL_TSI_YEAR\"",
    "\"SQL_VARBINARY\"",
    "\"SQL_VARCHAR\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STORE\"",
    "\"STREAM\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSET\"",
    "\"SUBSTITUTE\"",
    "\"SUBSTRING\"",
    "\"SUBSTRING_REGEX\"",
    "\"SUCCEEDS\"",
    "\"SUM\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_TIME\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPERATURE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TIMESTAMPADD\"",
    "\"TIMESTAMPDIFF\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATE_REGEX\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRIM_ARRAY\"",
    "\"TRUE\"",
    "\"TRUNCATE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNCONDITIONAL\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"UPSERT\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"UTF8\"",
    "\"UTF16\"",
    "\"UTF32\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VALUE_OF\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARBINARY\"",
    "\"VARCHAR\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VERSIONING\"",
    "\"VIDEO\"",
    "\"VIEW\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"ZONE\"",
    "\"IF\"",
    "\"STORED\"",
    "\"VIRTUAL\"",
    "\"JAR\"",
    "\"FILE\"",
    "\"ARCHIVE\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"||\"",
    "\"=>\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 744>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 749>",
    "<BRACKET_QUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<BACK_QUOTED_IDENTIFIER>",
    "<COLLATION_ID>",
    "<IDENTIFIER>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
