package org.polypheny.db.protointerface.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Polypheny-DB/plugins/proto-interface/src/main/proto/protointerface.proto

public interface ConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.polypheny.db.protointerface.proto.ConnectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 majorApiVersion = 1;</code>
   */
  int getMajorApiVersion();

  /**
   * <code>int32 minorApiVersion = 2;</code>
   */
  int getMinorApiVersion();

  /**
   * <pre>
   * UUID generated by the client. Enables the server to identify clients.
   * </pre>
   *
   * <code>string clientUUID = 3;</code>
   */
  String getClientUUID();
  /**
   * <pre>
   * UUID generated by the client. Enables the server to identify clients.
   * </pre>
   *
   * <code>string clientUUID = 3;</code>
   */
  com.google.protobuf.ByteString
      getClientUUIDBytes();

  /**
   * <code>map&lt;string, string&gt; connectionProperties = 4;</code>
   */
  int getConnectionPropertiesCount();
  /**
   * <code>map&lt;string, string&gt; connectionProperties = 4;</code>
   */
  boolean containsConnectionProperties(
      String key);
  /**
   * Use {@link #getConnectionPropertiesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getConnectionProperties();
  /**
   * <code>map&lt;string, string&gt; connectionProperties = 4;</code>
   */
  java.util.Map<String, String>
  getConnectionPropertiesMap();
  /**
   * <code>map&lt;string, string&gt; connectionProperties = 4;</code>
   */

  String getConnectionPropertiesOrDefault(
      String key,
      String defaultValue);
  /**
   * <code>map&lt;string, string&gt; connectionProperties = 4;</code>
   */

  String getConnectionPropertiesOrThrow(
      String key);
}
