package org.polypheny.db.protointerface.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Polypheny-DB/plugins/proto-interface/src/main/proto/protointerface.proto

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.polypheny.db.protointerface.proto.Frame)
    com.google.protobuf.MessageOrBuilder {
}
