// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Polypheny-DB/plugins/proto-interface/src/main/proto/protointerface.proto

package org.polypheny.db.protointerface.proto;

public final class ProtoInterfaceProto {
  private ProtoInterfaceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polypheny_protointerface_ConnectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polypheny_protointerface_ConnectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polypheny_protointerface_ConnectionRequest_ConnectionPropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polypheny_protointerface_ConnectionRequest_ConnectionPropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polypheny_protointerface_ConnectionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polypheny_protointerface_ConnectionReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polypheny_protointerface_SimpleSqlQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polypheny_protointerface_SimpleSqlQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polypheny_protointerface_QueryResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polypheny_protointerface_QueryResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polypheny_protointerface_Frame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polypheny_protointerface_Frame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polypheny_protointerface_setProperty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polypheny_protointerface_setProperty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\nHPolypheny-DB/plugins/proto-interface/s" +
      "rc/main/proto/protointerface.proto\022\030poly" +
      "pheny.protointerface\"\373\001\n\021ConnectionReque" +
      "st\022\027\n\017majorApiVersion\030\001 \001(\005\022\027\n\017minorApiV" +
      "ersion\030\002 \001(\005\022\022\n\nclientUUID\030\003 \001(\t\022c\n\024conn" +
      "ectionProperties\030\004 \003(\0132E.polypheny.proto" +
      "interface.ConnectionRequest.ConnectionPr" +
      "opertiesEntry\032;\n\031ConnectionPropertiesEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"Y\n\017Co" +
      "nnectionReply\022\024\n\014isCompatible\030\001 \001(\010\022\027\n\017m" +
      "ajorApiVersion\030\002 \001(\r\022\027\n\017minorApiVersion\030" +
      "\003 \001(\r\"\037\n\016SimpleSqlQuery\022\r\n\005query\030\001 \001(\t\"\202" +
      "\001\n\013QueryResult\022\022\n\010noResult\030\001 \001(\010H\000\0220\n\005fr" +
      "ame\030\002 \001(\0132\037.polypheny.protointerface.Fra" +
      "meH\000\022\017\n\005count\030\003 \001(\005H\000\022\022\n\010bigCount\030\004 \001(\003H" +
      "\000B\010\n\006result\"\007\n\005Frame\")\n\013setProperty\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t2\341\001\n\016ProtoInterfa" +
      "ce\022c\n\007connect\022+.polypheny.protointerface" +
      ".ConnectionRequest\032).polypheny.protointe" +
      "rface.ConnectionReply\"\000\022j\n\025executeSimple" +
      "SqlQuery\022(.polypheny.protointerface.Simp" +
      "leSqlQuery\032%.polypheny.protointerface.Qu" +
      "eryResult\"\000BC\n%org.polypheny.db.protoint" +
      "erface.protoB\023ProtoInterfaceProtoP\001\242\002\002PI" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_polypheny_protointerface_ConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_polypheny_protointerface_ConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polypheny_protointerface_ConnectionRequest_descriptor,
        new String[] { "MajorApiVersion", "MinorApiVersion", "ClientUUID", "ConnectionProperties", });
    internal_static_polypheny_protointerface_ConnectionRequest_ConnectionPropertiesEntry_descriptor =
      internal_static_polypheny_protointerface_ConnectionRequest_descriptor.getNestedTypes().get(0);
    internal_static_polypheny_protointerface_ConnectionRequest_ConnectionPropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polypheny_protointerface_ConnectionRequest_ConnectionPropertiesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_polypheny_protointerface_ConnectionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_polypheny_protointerface_ConnectionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polypheny_protointerface_ConnectionReply_descriptor,
        new String[] { "IsCompatible", "MajorApiVersion", "MinorApiVersion", });
    internal_static_polypheny_protointerface_SimpleSqlQuery_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_polypheny_protointerface_SimpleSqlQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polypheny_protointerface_SimpleSqlQuery_descriptor,
        new String[] { "Query", });
    internal_static_polypheny_protointerface_QueryResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_polypheny_protointerface_QueryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polypheny_protointerface_QueryResult_descriptor,
        new String[] { "NoResult", "Frame", "Count", "BigCount", "Result", });
    internal_static_polypheny_protointerface_Frame_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_polypheny_protointerface_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polypheny_protointerface_Frame_descriptor,
        new String[] { });
    internal_static_polypheny_protointerface_setProperty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_polypheny_protointerface_setProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polypheny_protointerface_setProperty_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
