// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Polypheny-DB/plugins/proto-interface/src/main/proto/protointerface.proto

package org.polypheny.db.protointerface.proto;

public interface QueryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polypheny.protointerface.QueryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool noResult = 1;</code>
   */
  boolean getNoResult();

  /**
   * <code>.polypheny.protointerface.Frame frame = 2;</code>
   */
  boolean hasFrame();
  /**
   * <code>.polypheny.protointerface.Frame frame = 2;</code>
   */
  Frame getFrame();
  /**
   * <code>.polypheny.protointerface.Frame frame = 2;</code>
   */
  FrameOrBuilder getFrameOrBuilder();

  /**
   * <code>int32 count = 3;</code>
   */
  int getCount();

  /**
   * <code>int64 bigCount = 4;</code>
   */
  long getBigCount();

  public QueryResult.ResultCase getResultCase();
}
