name: Polypheny-DB Docker CI

on:
    push:
    pull_request:
        types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
    build:
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
        runs-on: ubuntu-latest
        name: Docker Tests (Java 11)
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Set up JDK
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: 11
            -   name: Set env variable
                run: |
                    echo "POLYPHENY_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
            -   name: Assemble
                uses: nick-invision/retry@v2
                with:
                    max_attempts: 2
                    timeout_minutes: 60
                    command: ./gradlew assemble
            -   name: Build Plugins
                uses: nick-invision/retry@v2
                with:
                    max_attempts: 1
                    timeout_minutes: 60
                    command: ./gradlew assemblePlugins
            -   name: Execute Docker tests
                uses: nick-invision/retry@v2
                with:
                    max_attempts: 2
                    timeout_minutes: 25
                    command: ./gradlew dockerTests
