name: Polypheny-DB MQTT Client Test

on:
    push: { branches: mqtt-interface }

jobs:
    build:
        runs-on: ubuntu-latest
        name: MQTT Client Tests (Java 17)
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 17
            -   name: Set env variable
                run: |
                    echo "POLYPHENY_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
            -   name: Create folders for certs
                run: |
                    mkdir $POLYPHENY_HOME/.polypheny
                    mkdir $POLYPHENY_HOME/.polypheny/certs

            -   name: Start Mosquitto broker in docker container
                uses: namoshek/mosquitto-github-action@v1
                with:
                    version: '1.6'
                    ports: '1883:1883'
                    container-name: 'mqttBroker'

            -   name: Assemble
                uses: nick-invision/retry@v2
                with:
                    max_attempts: 2
                    timeout_minutes: 60
                    command: ./gradlew assemble

            - name: Build Plugins
              uses: nick-invision/retry@v2
              with:
                  max_attempts: 1
                  timeout_minutes: 60
                  command: ./gradlew assemblePlugins

            -   name: Execute MQTT client tests
                uses: nick-invision/retry@v2
                with:
                    max_attempts: 1
                    timeout_minutes: 30
                    command: ./gradlew mqttTests